### ISSUE TITLE
SDK怎么没有相关文档

### ISSUE THREAD

**Issue by jiangyue008** [PaienNate/dolphinscheduler-sdk-go#1]

**Comment by PaienNate** [comment]
没有就对了，因为这是个半成品，当时想的是把Java的代码转换过来，结果后来我们开发着开发着把DolphinScheduler丢出去了，这项目就搁浅了。
只有一两个路能用（记得是能提任务）

**Comment by PaienNate** [comment]
以及指路:https://github.com/weaksloth/dolphinscheduler-sdk-java

**Comment by jiangyue008** [comment]
我看看是用官方的python还是java版本的。我们这边开发人员能力有限，自己搞估计够呛

**Comment by PaienNate** [comment]
> 我看看是用官方的python还是java版本的。我们这边开发人员能力有限，自己搞估计够呛

我用过java的感觉还可以，python的我没跑通。python的不知道是有什么特殊问题……

java的本质就是请求swagger接口。

理论上你们需求功能少的话自己写一下也不是不行。需要功能太多的话，把sdk封装成api调用没准都比写这个强（叹气）

**Comment by jiangyue008** [comment]
好的，谢谢
